(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g=this||self,l=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var m={},n=null,p=function(a){var c;void 0===c&&(c=0);if(!n){n={};for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=d.concat(b[e].split(""));m[e]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===n[k]&&(n[k]=h)}}}c=m[c];d=Array(Math.floor(a.length/3));b=c[64]||"";for(e=f=0;f<a.length-2;f+=3){var E=a[f],F=a[f+1];k=a[f+2];h=c[E>>2];E=c[(E&3)<<4|F>>4];F=c[(F&15)<<2|k>>6];k=c[k&63];d[e++]=""+h+E+F+k}h=0;k=b;switch(a.length-
f){case 2:h=a[f+1],k=c[(h&15)<<2]||b;case 1:a=a[f],d[e]=""+c[a>>2]+c[(a&3)<<4|h>>4]+k+b}return d.join("")};var q="function"===typeof Uint8Array;let r;var t=class{constructor(){this.g=null}};r||(r=new t);const u="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function v(a){Object.isFrozen(a)||(u?a[u]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function w(a){return null!==a&&"object"===typeof a&&a.constructor===Object}let x;function y(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(q&&null!=a&&a instanceof Uint8Array)return p(a);if(a instanceof t){if(null==a.g)a="";else{var c=a.g;c=null==c||"string"===typeof c?c:q&&c instanceof Uint8Array?p(c):null;a=a.g=c}return a}}return a};function z(a,c){if(null!=a)return Array.isArray(a)||w(a)?A(a,c):c(a)}function A(a,c){if(Array.isArray(a)){var d=Array(a.length);for(let e=0;e<a.length;e++)d[e]=z(a[e],c);if(c=Array.isArray(a)){var b;u?b=a[u]:b=a.g;c=(null==b?0:b)&1}c&&v(d);return d}b={};for(d in a)b[d]=z(a[d],c);return b}function B(a){a=y(a);return Array.isArray(a)?A(a,B):a};let C;var G=function(a,c,d){var b=C;C=null;a||(a=b);b=this.constructor.u;a||(a=b?[b]:[]);this.j=(b?0:-1)-(this.constructor.o||0);this.g=null;this.h=a;a:{b=this.h.length;a=b-1;if(b&&(b=this.h[a],w(b))){this.l=a-this.j;this.i=b;break a}void 0!==c&&-1<c?(this.l=Math.max(c,a+1-this.j),this.i=null):this.l=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)a=d[c],a<this.l?(a+=this.j,(b=this.h[a])?Array.isArray(b)&&v(b):this.h[a]=D):(ba(this),(b=this.i[a])?Array.isArray(b)&&v(b):this.i[a]=D)};
const D=Object.freeze(v([])),ba=function(a){let c=a.l+a.j;a.h[c]||(a.i=a.h[c]={})};
var H=function(a,c,d=!1){return-1===c?null:d||c>=a.l?a.i?a.i[c]:void 0:a.h[c+a.j]},I=function(a,c,d=!1){a=H(a,c);a=null==a?a:!!a;return null==a?d:a},J=function(a,c,d,b=!1){b||c>=a.l?(ba(a),a.i[c]=d):a.h[c+a.j]=d;return a},K=function(a,c){let d=0;for(let b=0;b<c.length;b++){const e=c[b];null!=H(a,e)&&(0!==d&&J(a,d,void 0,!1),d=e)}return d},L=function(a,c,d){if(-1===d)return null;a.g||(a.g={});const b=a.g[d];if(b)return b;let e=H(a,d,!1);if(null==e)return b;c=new c(e);return a.g[d]=c},da=function(a,
c){var d=ca;a.g||(a.g={});var b=a.g[c];if(!b){b=H(a,c,!1);null==b&&(b=D);b===D&&(b=v(b.slice()),J(a,c,b,!1));var e=b;b=[];for(let f=0;f<e.length;f++)b[f]=new d(e[f]);a.g[c]=b}return b};G.prototype.toJSON=function(){const a=this.h;return x?a:A(a,B)};function ea(a,c){return y(c)}G.prototype.toString=function(){return this.h.toString()};function M(a,c,d){return K(a,c)===d?d:-1}var N=function(a,c,d=0){a=H(a,c);return null==a?d:a},O=function(a,c,d=""){a=H(a,c);return null==a?d:a};var ca=class extends G{constructor(a){super(a)}},P=[2,3,4];var fa=class extends G{constructor(a){super(a)}};var Q=class extends G{constructor(a){super(a)}};var ia=class extends G{constructor(a){super(a,-1,ha)}},ha=[6];var ja=class extends G{constructor(){super(void 0)}};var ka=class extends G{constructor(){super(void 0)}},la=[2];var na=class extends G{constructor(a){super(a,-1,ma)}},ma=[2];var oa=class extends G{constructor(a){super(a)}};var pa=class extends G{constructor(a){super(a)}};var qa=class extends G{constructor(a){super(a)}};var ra=class extends G{constructor(a){super(a)}},R=[2,3,4,5,6,7];var S;var T=function(a,c){this.h=a===sa&&c||"";this.g=ta},ta={},sa={};var U=class{constructor(a,c){this.g=c===ua?a:""}};U.prototype.toString=function(){return this.g+""};var ua={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var V=function(){this.g=document||{cookie:""}};
V.prototype.set=function(a,c,d){let b,e,f,h=!1,k;"object"===typeof d&&(k=d.v,h=d.A||!1,f=d.domain||void 0,e=d.path||void 0,b=d.s);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(c))throw Error('Invalid cookie value "'+c+'"');void 0===b&&(b=-1);this.g.cookie=a+"="+c+(f?";domain="+f:"")+(e?";path="+e:"")+(0>b?"":0==b?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*b)).toUTCString())+(h?";secure":"")+(null!=k?";samesite="+k:"")};
V.prototype.get=function(a,c){const d=a+"=",b=(this.g.cookie||"").split(";");for(let e=0,f;e<b.length;e++){f=aa(b[e]);if(0==f.lastIndexOf(d,0))return f.substr(d.length);if(f==a)return""}return c};class W{constructor(){this.h=new V;this.g="";this.i=a=>{a:{let h;try{var c=a.data,d=c?JSON.parse(c):null;C=d;const k=new ra(d);C=null;h=k}catch(k){break a}if(4===K(h,R)){var b=L(h,ia,M(h,R,4)),e=da(b,6),f;e.length&&(f=va(e));f={event:O(b,1)||void 0,category:O(b,2)||void 0,action:O(b,3)||void 0,label:O(b,4)||void 0,value:N(b,5)||void 0,additionalParams:f||void 0};null!=H(b,12)?(e=L(b,Q,12),f.recommendations={targetPage:O(e,1),targetType:N(e,2),targetRank:N(e,3),targetIdenticalDescriptions:N(e,4),targetTitleWords:N(e,
5),targetDescriptionWords:N(e,6),experiment:O(e,7)}):f.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};null!=H(b,11)&&(b=L(b,fa,11),f.practitionerType=O(b,1)||"Property not set",f.profileCreationMethod=O(b,4)||"Property not set",f.profileBadgeEmailOptIn=I(b,5)?"True":"False",f.profileFeedbackEmailOptIn=I(b,2)?"True":"False",f.profileNewsletterEmailOptIn=I(b,3)?"True":"False");window.dataLayer.push(f)}else if(3===
K(h,R))b=L(h,na,M(h,R,3)),f=da(b,2),f.length&&(e=va(f)),f={event:"trackPageview",pageName:O(b,1),additionalParams:e||void 0,nonInteraction:I(b,3)||void 0,ratingsCount:N(b,4)||void 0,ratingsValue:N(b,5)||void 0},null!=H(b,6)&&(b=L(b,fa,6),f.practitionerType=O(b,1)||"Property not set",f.profileCreationMethod=O(b,4)||"Property not set",f.profileBadgeEmailOptIn=I(b,5)?"True":"False",f.profileFeedbackEmailOptIn=I(b,2)?"True":"False",f.profileNewsletterEmailOptIn=I(b,3)?"True":"False"),window.dataLayer.push(f);
else if(7===K(h,R))b=L(h,oa,M(h,R,7)),window.dataLayer.push({parentContext:{referrer:O(b,2)||"",_ga_devsiteCookie:O(b,1)||""}});else if(6===K(h,R))b=L(h,pa,M(h,R,6)),f=this.g,e=L(b,Q,9)||new Q,window.dataLayer.push({hostContext:{internalUser:O(b,1)||void 0,pageType:O(b,8)||void 0,projectName:O(b,6)||void 0,signedIn:O(b,2)||void 0,tenant:O(b,5)||void 0,thirdPartyCookieAccepted:f.length?"True":"False"},language:{machineTranslated:O(b,7)||void 0,requested:O(b,3)||void 0,served:O(b,4)||void 0},recommendations:{sourcePage:O(e,
1),sourceType:N(e,2),sourceRank:N(e,3),sourceIdenticalDescriptions:N(e,4),sourceTitleWords:N(e,5),sourceDescriptionWords:N(e,6),experiment:O(e,7)}});else if(5===K(h,R))b=L(h,qa,M(h,R,5)),window.dataLayer.push({originalUrlParameters:{dclid:O(b,1)||void 0,gclid:O(b,2)||void 0,utmCampaign:O(b,3)||void 0,utmContent:O(b,4)||void 0,utmMedium:O(b,5)||void 0,utmSource:O(b,6)||void 0,utmTerm:O(b,7)||void 0}});else if(2===K(h,R)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),
event:"gtm.js"});f=document.getElementsByTagName("script")[0];e=document.createElement("script");e.async=!0;a=new T(sa,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");a=a instanceof T&&a.constructor===T&&a.g===ta?a.h:"type_error:Const";if(void 0===S)if(c=null,(d=g.trustedTypes)&&d.createPolicy){try{c=d.createPolicy("goog#html",{createHTML:l,createScript:l,createScriptURL:l})}catch(k){g.console&&g.console.error(k.message)}S=c}else S=c;a=(c=S)?c.createScriptURL(a):a;c=new U(a,ua);a=e;a.src=c instanceof
U&&c.constructor===U?c.g:"type_error:TrustedResourceUrl";c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document;(b=(d=null===(b=c.querySelector)||void 0===b?void 0:b.call(c,"script[nonce]"))?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b);f.parentNode.insertBefore(e,f)}}};window.addEventListener("message",this.i)}m(a){this.g=this.h.get("_ga_devsite")||"";var c=new ja;!1!==a?J(c,1,a):J(c,1,void 0,!1);a=this.g;""!==a?J(c,2,a):J(c,2,void 0,!1);a=new ka;a.g||(a.g={});var d=
c?c.h:c;a.g[2]=c;(c=K(a,la))&&2!==c&&null!=d&&(a.g&&c in a.g&&(a.g[c]=void 0),J(a,c,void 0));c=J(a,2,d);if(window.parent!==window){a=window.parent;d=a.postMessage;a:{x=!0;try{var b=JSON.stringify(c.toJSON(),ea);break a}finally{x=!1}b=void 0}d.call(a,b,"*")}}}W.prototype.notifyIframeReady=W.prototype.m;
function va(a){const c={};for(const d of a){a=O(d,1);let b;O(d,M(d,P,2),void 0)?b=O(d,M(d,P,2),void 0):N(d,M(d,P,3),void 0)?b=N(d,M(d,P,3),void 0):4===K(d,P)&&(b=I(d,M(d,P,4),void 0)?"True":"False");c[a]=b}return c}var wa=W,X=["AnalyticsLibrary"],Y=g;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===wa?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=wa;}).call(this);
