(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d=this||self,l=function(a,b){a=a.split(".");var c=d;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=b},n=function(a){return a};var p=new Map([]);p.set("devsite-a11y-announce",{src:"/developers/js/devsite_devsite_a11y_announce_module.js"});p.set("devsite-analytics",{src:"/developers/js/devsite_devsite_analytics_module.js"});p.set("devsite-analytics-scope",{src:"/developers/js/devsite_devsite_analytics_scope_module.js"});p.set("devsite-anselm",{src:"/developers/js/devsite_devsite_anselm_module.js"});p.set("devsite-api-getstarted",{src:"/developers/js/devsite_devsite_api_getstarted_module.js"});p.set("devsite-apix",{src:"/developers/js/devsite_devsite_apix_module.js"});
p.set("devsite-apix-index",{src:"/developers/js/devsite_devsite_apix_index_module.js"});p.set("devsite-apix-snippets",{src:"/developers/js/devsite_devsite_apix_snippets_module.js"});p.set("devsite-badger",{src:"/developers/js/devsite_devsite_badger_module.js"});p.set("devsite-badge-awarded",{src:"/developers/js/devsite_devsite_badge_awarded_module.js"});p.set("devsite-badge-awarder",{src:"/developers/js/devsite_devsite_badge_awarder_module.js"});p.set("devsite-badge-redeemer",{src:"/developers/js/devsite_devsite_badge_redeemer_module.js"});
p.set("devsite-book-nav",{src:"/developers/js/devsite_devsite_book_nav_module.js"});p.set("devsite-bookmark",{src:"/developers/js/devsite_devsite_bookmark_module.js"});p.set("devsite-chart",{src:"/developers/js/devsite_devsite_chart_module.js"});p.set("devsite-catalog",{src:"/developers/js/devsite_devsite_catalog_module.js"});p.set("devsite-code",{src:"/developers/js/devsite_devsite_code_module.js"});p.set("devsite-content",{src:"/developers/js/devsite_devsite_content_module.js"});
p.set("devsite-codelab-catalog",{src:"/developers/js/devsite_devsite_codelab_catalog_module.js"});p.set("devsite-credentials-dialog",{src:"/developers/js/devsite_devsite_credentials_dialog_module.js"});p.set("devsite-cse",{src:"/developers/js/devsite_devsite_cse_module.js"});p.set("devsite-device",{src:"/developers/js/devsite_devsite_device_module.js"});p.set("devsite-devprofile",{src:"/developers/js/devsite_devsite_devprofile_module.js"});p.set("devsite-dialog",{src:"/developers/js/devsite_devsite_dialog_module.js"});
p.set("devsite-dynamic-content",{src:"/developers/js/devsite_devsite_dynamic_content_module.js"});p.set("devsite-expandable",{src:"/developers/js/devsite_devsite_expandable_module.js"});p.set("devsite-expandable-nav",{src:"/developers/js/devsite_devsite_expandable_nav_module.js"});p.set("devsite-extradory",{src:"/developers/js/devsite_devsite_extradory_module.js"});p.set("devsite-feedback",{src:"/developers/js/devsite_devsite_feedback_module.js"});p.set("devsite-filter",{src:"/developers/js/devsite_devsite_filter_module.js"});
p.set("devsite-footer-linkboxes",{src:"/developers/js/devsite_devsite_footer_linkboxes_module.js"});p.set("devsite-footer-promos",{src:"/developers/js/devsite_devsite_footer_promos_module.js"});p.set("devsite-footer-utility",{src:"/developers/js/devsite_devsite_footer_utility_module.js"});p.set("devsite-google-survey",{src:"/developers/js/devsite_devsite_google_survey_module.js"});p.set("devsite-googler-buttons",{src:"/developers/js/devsite_devsite_googler_buttons_module.js"});
p.set("devsite-hats-survey",{src:"/developers/js/devsite_devsite_hats_survey_module.js"});p.set("devsite-header",{src:"/developers/js/devsite_devsite_header_module.js"});p.set("devsite-heading-link",{src:"/developers/js/devsite_devsite_heading_link_module.js"});p.set("devsite-iframe",{src:"/developers/js/devsite_devsite_iframe_module.js"});p.set("devsite-info-popout",{src:"/developers/js/devsite_devsite_info_popout_module.js"});p.set("devsite-jump-to",{src:"/developers/js/devsite_devsite_jump_to_module.js"});
p.set("devsite-jsfiddle-button",{src:"/developers/js/devsite_devsite_jsfiddle_button_module.js"});p.set("devsite-language-selector",{src:"/developers/js/devsite_devsite_language_selector_module.js"});p.set("devsite-lightbox",{src:"/developers/js/devsite_devsite_lightbox_module.js"});p.set("devsite-mathjax",{src:"/developers/js/devsite_devsite_mathjax_module.js"});p.set("devsite-mdc",{src:"/developers/js/devsite_devsite_mdc_module.js"});p.set("devsite-multiple-choice",{src:"/developers/js/devsite_devsite_multiple_choice_module.js"});
p.set("devsite-nav-buttons",{src:"/developers/js/devsite_devsite_nav_buttons_module.js"});p.set("devsite-pagination",{src:"/developers/js/devsite_devsite_pagination_module.js"});p.set("devsite-panel",{src:"/developers/js/devsite_devsite_panel_module.js"});p.set("devsite-playlist",{src:"/developers/js/devsite_devsite_playlist_module.js"});p.set("devsite-playlist-earnable-badges",{src:"/developers/js/devsite_devsite_playlist_earnable_badges_module.js"});p.set("devsite-playlist-summary",{src:"/developers/js/devsite_devsite_playlist_summary_module.js"});
p.set("devsite-product-catalog",{src:"/developers/js/devsite_devsite_product_catalog_module.js"});p.set("devsite-profile-card",{src:"/developers/js/devsite_devsite_profile_card_module.js"});p.set("devsite-progress",{src:"/developers/js/devsite_devsite_progress_module.js"});p.set("devsite-quiz",{src:"/developers/js/devsite_devsite_quiz_module.js"});p.set("devsite-recommendations",{src:"/developers/js/devsite_devsite_recommendations_module.js"});p.set("devsite-recommendations-dropdown",{src:"/developers/js/devsite_devsite_recommendations_dropdown_module.js"});
p.set("devsite-recommendations-sidebar",{src:"/developers/js/devsite_devsite_recommendations_sidebar_module.js"});p.set("devsite-reference-results",{src:"/developers/js/devsite_devsite_reference_results_module.js"});p.set("devsite-search",{src:"/developers/js/devsite_devsite_search_module.js"});p.set("devsite-select",{src:"/developers/js/devsite_devsite_select_module.js"});p.set("devsite-selector",{src:"/developers/js/devsite_devsite_selector_module.js"});p.set("devsite-shell",{src:"/developers/js/devsite_devsite_shell_module.js"});
p.set("devsite-shell-activate-button",{src:"/developers/js/devsite_devsite_shell_activate_button_module.js"});p.set("devsite-sitemask",{src:"/developers/js/devsite_devsite_sitemask_module.js"});p.set("devsite-snackbar",{src:"/developers/js/devsite_devsite_snackbar_module.js"});p.set("devsite-sort",{src:"/developers/js/devsite_devsite_sort_module.js"});p.set("devsite-spinner",{src:"/developers/js/devsite_devsite_spinner_module.js"});p.set("devsite-support-form",{src:"/developers/js/devsite_devsite_support_form_module.js"});
p.set("devsite-tabs",{src:"/developers/js/devsite_devsite_tabs_module.js"});p.set("devsite-theme-selector",{src:"/developers/js/devsite_devsite_theme_selector_module.js"});p.set("devsite-thumb-rating",{src:"/developers/js/devsite_devsite_thumb_rating_module.js"});p.set("devsite-toc",{src:"/developers/js/devsite_devsite_toc_module.js"});p.set("devsite-topic",{src:"/developers/js/devsite_devsite_topic_module.js"});p.set("devsite-tooltip",{src:"/developers/js/devsite_devsite_tooltip_module.js"});
p.set("devsite-tracking-question",{src:"/developers/js/devsite_devsite_tracking_question_module.js"});p.set("devsite-user",{src:"/developers/js/devsite_devsite_user_module.js"});p.set("devsite-var",{src:"/developers/js/devsite_devsite_var_module.js"});p.set("devsite-version-selector",{src:"/developers/js/devsite_devsite_version_selector_module.js"});p.set("devsite-visibility-analytics",{src:"/developers/js/devsite_devsite_visibility_analytics_module.js"});p.set("devsite-vplus",{src:"/developers/js/devsite_devsite_vplus_module.js"});
p.set("devsite-wall-acknowledgement",{src:"/developers/js/devsite_devsite_wall_acknowledgement_module.js"});p.set("devsite-youtube",{src:"/developers/js/devsite_devsite_youtube_module.js"});p.set("google-codelab",{src:"/developers/js/devsite_google_codelab_module.js"});p.set("google-codelab-about",{src:"/developers/js/devsite_google_codelab_about_module.js"});p.set("google-codelab-analytics",{src:"/developers/js/devsite_google_codelab_analytics_module.js"});p.set("google-codelab-step",{src:"/developers/js/devsite_google_codelab_step_module.js"});
p.set("google-codelab-survey",{src:"/developers/js/devsite_google_codelab_survey_module.js"});p.set("devsite-avatar",{src:"/developers/js/devsite_devsite_avatar_module.js"});p.set("devsite-activity-list",{src:"/developers/js/devsite_devsite_activity_list_module.js"});p.set("devsite-badge",{src:"/developers/js/devsite_devsite_badge_module.js"});p.set("devsite-mwc",{src:"/developers/js/devsite_devsite_mwc_module.js"});p.set("devsite-profile",{src:"/developers/js/devsite_devsite_profile_module.js"});
p.set("devsite-profile-dashboard",{src:"/developers/js/devsite_devsite_profile_dashboard_module.js"});p.set("devsite-profile-interests",{src:"/developers/js/devsite_devsite_profile_interests_module.js"});p.set("devsite-profile-recommendations",{src:"/developers/js/devsite_devsite_profile_recommendations_module.js"});p.set("devsite-profile-wizard",{src:"/developers/js/devsite_devsite_profile_wizard_module.js"});p.set("devsite-profile-router",{src:"/developers/js/devsite_devsite_profile_router_module.js"});
p.set("devsite-profiles-splash",{src:"/developers/js/devsite_devsite_profiles_splash_module.js"});l("DevsiteAppAuthorizedElements",p);l("DevsiteAppTenantCustomized",!0);var q={Mb:0,Lb:1,rb:6,pb:8,wb:12,xb:14,yb:17,Bb:18,Db:21,Fb:25,da:37,Gb:38,pa:40,Qa:45,P:47,v:50,J:52,G:62,Ca:63,lb:66,ab:70,A:73,Va:74,S:75,ib:76,ya:77,Aa:80,H:81,Na:82,wa:83,$a:85,X:87,ra:89,cb:90,sa:91,za:92,N:93,Jb:94,va:95,M:96,mb:97,B:98,D:99,Eb:100,oa:101,xa:102,hb:103,Ib:104,Z:105,O:106,ma:107,ba:108,Za:109,Y:110,ka:111,Hb:112,jb:113,ca:114,L:115,fa:116,Oa:117,Ma:118,ta:119,bb:120,ub:121,kb:122,zb:123,qb:124,Ja:125,Wa:126,na:127,vb:128,Sa:129,Ta:130,ia:131,Ha:132,C:133,Da:134,qa:135,Pa:136,
F:137,Kb:138,Xa:139,sb:140,ob:141,Ra:142,La:143,Ya:144,K:145,Ua:146,Ea:147,Ka:148,eb:149,aa:150,W:151,Fa:152,ja:153,ha:154,R:155,Cb:156,Ab:157,Ba:158,ga:159,I:160,T:161,$:162,tb:163,gb:164,ea:165,U:166,nb:167,V:168,Ia:169,Ga:170,ua:171,la:172,fb:173};var r={},t=null,u=function(a){var b;void 0===b&&(b=0);if(!t){t={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),e=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var g=c.concat(e[f].split(""));r[f]=g;for(var h=0;h<g.length;h++){var k=g[h];void 0===t[k]&&(t[k]=h)}}}b=r[b];c=Array(Math.floor(a.length/3));e=b[64]||"";for(f=g=0;g<a.length-2;g+=3){var m=a[g],C=a[g+1];k=a[g+2];h=b[m>>2];m=b[(m&3)<<4|C>>4];C=b[(C&15)<<2|k>>6];k=b[k&63];c[f++]=""+h+m+C+k}h=0;k=e;switch(a.length-
g){case 2:h=a[g+1],k=b[(h&15)<<2]||e;case 1:a=a[g],c[f]=""+b[a>>2]+b[(a&3)<<4|h>>4]+k+e}return c.join("")};var v="function"===typeof Uint8Array;let w;var x=class{constructor(){this.g=null}};w||(w=new x);const y="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function z(a){Object.isFrozen(a)||(y?a[y]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function A(a){return null!==a&&"object"===typeof a&&a.constructor===Object}let B;function D(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(v&&null!=a&&a instanceof Uint8Array)return u(a);if(a instanceof x){if(null==a.g)a="";else{var b=a.g;b=null==b||"string"===typeof b?b:v&&b instanceof Uint8Array?u(b):null;a=a.g=b}return a}}return a};function E(a,b){if(null!=a)return Array.isArray(a)||A(a)?F(a,b):b(a)}function F(a,b){if(Array.isArray(a)){var c=Array(a.length);for(let f=0;f<a.length;f++)c[f]=E(a[f],b);if(b=Array.isArray(a)){var e;y?e=a[y]:e=a.g;b=(null==e?0:e)&1}b&&z(c);return c}e={};for(c in a)e[c]=E(a[c],b);return e}function G(a){a=D(a);return Array.isArray(a)?F(a,G):a};let H;var K=function(a){var b=aa,c=H;H=null;a||(a=c);c=this.constructor.Ob;a||(a=c?[c]:[]);this.i=(c?0:-1)-(this.constructor.Nb||0);this.g=a;a:{c=this.g.length;a=c-1;if(c&&(c=this.g[a],A(c))){this.j=a-this.i;this.h=c;break a}this.j=Number.MAX_VALUE}if(b)for(a=0;a<b.length;a++)if(c=b[a],c<this.j){c+=this.i;var e=this.g[c];e?Array.isArray(e)&&z(e):this.g[c]=I}else J(this),(e=this.h[c])?Array.isArray(e)&&z(e):this.h[c]=I};const I=Object.freeze(z([])),J=function(a){let b=a.j+a.i;a.g[b]||(a.h=a.g[b]={})};
var L=function(a,b,c=!1){return-1===b?null:c||b>=a.j?a.h?a.h[b]:void 0:a.g[b+a.i]},N=function(a,b){let c=L(a,b,!1);null==c&&(c=I);c===I&&(c=z(c.slice()),M(a,b,c,!1));return c},O=function(a,b){a=L(a,b);a=null==a?a:!!a;return null==a?!1:a},M=function(a,b,c,e=!1){e||b>=a.j?(J(a),a.h[b]=c):a.g[b+a.i]=c};K.prototype.toJSON=function(){const a=this.g;return B?a:F(a,G)};function ba(a,b){return D(b)}var ca=function(){var a=P.g;B=!0;try{return JSON.stringify(a.toJSON(),ba)}finally{B=!1}};
K.prototype.toString=function(){return this.g.toString()};var Q=function(a,b){a=L(a,b);return null==a?"":a};var ea=function(){var a=`${GoogleDevelopersObject}`.replace("\n",""),b=da;H=a=a?JSON.parse(a):null;b=new b(a);H=null;return b},da=class extends K{getTenantId(){let a=L(this,1);return null==a?0:a}getLocale(){return Q(this,2)}getInsecureHost(){return Q(this,7)}},aa=[10,12,13];var R;var S=class{constructor(a,b){this.g=b===fa?a:""}};S.prototype.toString=function(){return this.g+""};var fa={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var ha=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),ia=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var e=a[c].indexOf("="),f=null;if(0<=e){var g=a[c].substring(0,e);f=a[c].substring(e+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var T=function(a,b){this.j=this.s=this.i="";this.o=null;this.l=this.m="";this.g=!1;if(a instanceof T){this.g=void 0!==b?b:a.g;ja(this,a.i);this.s=a.s;this.j=a.j;ka(this,a.o);this.m=a.m;b=a.h;var c=new U;c.i=b.i;b.g&&(c.g=new Map(b.g),c.h=b.h);la(this,c);this.l=a.l}else a&&(c=String(a).match(ha))?(this.g=!!b,ja(this,c[1]||"",!0),this.s=V(c[2]||""),this.j=V(c[3]||"",!0),ka(this,c[4]),this.m=V(c[5]||"",!0),la(this,c[6]||"",!0),this.l=V(c[7]||"")):(this.g=!!b,this.h=new U(null,this.g))};
T.prototype.toString=function(){var a=[],b=this.i;b&&a.push(W(b,ma,!0),":");var c=this.j;if(c||"file"==b)a.push("//"),(b=this.s)&&a.push(W(b,ma,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,null!=c&&a.push(":",String(c));if(c=this.m)this.j&&"/"!=c.charAt(0)&&a.push("/"),a.push(W(c,"/"==c.charAt(0)?na:oa,!0));(c=this.h.toString())&&a.push("?",c);(c=this.l)&&a.push("#",W(c,pa));return a.join("")};
var ja=function(a,b,c){a.i=c?V(b,!0):b;a.i&&(a.i=a.i.replace(/:$/,""))},ka=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},la=function(a,b,c){b instanceof U?(a.h=b,qa(a.h,a.g)):(c||(b=W(b,ra)),a.h=new U(b,a.g))},sa=function(a){return a instanceof T?new T(a):new T(a,void 0)},V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},W=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,ta),c&&(a=
a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},ta=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},ma=/[#\/\?@]/g,oa=/[#\?:]/g,na=/[#\?]/g,ra=/[#\?@]/g,pa=/#/g,U=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},X=function(a){a.g||(a.g=new Map,a.h=0,a.i&&ia(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};
U.prototype.add=function(a,b){X(this);this.i=null;a=Y(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};var ua=function(a,b){X(a);b=Y(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))},va=function(a,b){X(a);b=Y(a,b);return a.g.has(b)};U.prototype.forEach=function(a,b){X(this);this.g.forEach(function(c,e){c.forEach(function(f){a.call(b,f,e,this)},this)},this)};
var wa=function(a,b){X(a);let c=[];if("string"===typeof b)va(a,b)&&(c=c.concat(a.g.get(Y(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};U.prototype.set=function(a,b){X(this);this.i=null;a=Y(this,a);va(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};U.prototype.get=function(a,b){if(!a)return b;a=wa(this,a);return 0<a.length?String(a[0]):b};
U.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var e=b[c];const g=encodeURIComponent(String(e)),h=wa(this,e);for(e=0;e<h.length;e++){var f=g;""!==h[e]&&(f+="="+encodeURIComponent(String(h[e])));a.push(f)}}return this.i=a.join("&")};
var Y=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},qa=function(a,b){b&&!a.j&&(X(a),a.i=null,a.g.forEach(function(c,e){var f=e.toLowerCase();if(e!=f&&(ua(this,e),ua(this,f),0<c.length)){this.i=null;e=this.g;var g=e.set;f=Y(this,f);var h=c.length;if(0<h){const k=Array(h);for(let m=0;m<h;m++)k[m]=c[m];h=k}else h=[];g.call(e,f,h);this.h+=c.length}},a));a.j=b};const xa={};function ya(a,b){var c=xa[a];if(void 0!==c&&(!c.u||Date.now()<=c.u+3E5))return c.p;c=new Promise((f,g)=>{b.onload=()=>f(b);b.onerror=h=>{b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});const e={u:0,p:c};c.catch(()=>e.u=+new Date);xa[a]=e;return c}
var za=function(a){a=sa(a);const b=document.createElement("script");var c=a.toString();if(void 0===R){var e=null;var f=d.trustedTypes;if(f&&f.createPolicy){try{e=f.createPolicy("goog#html",{createHTML:n,createScript:n,createScriptURL:n})}catch(h){d.console&&d.console.error(h.message)}R=e}else R=e}c=(e=R)?e.createScriptURL(c):c;c=new S(c,fa);b.src=c instanceof S&&c.constructor===S?c.g:"type_error:TrustedResourceUrl";var g;c=(b.ownerDocument&&b.ownerDocument.defaultView||window).document;(g=(e=null===
(g=c.querySelector)||void 0===g?void 0:g.call(c,"script[nonce]"))?e.nonce||e.getAttribute("nonce")||"":"")&&b.setAttribute("nonce",g);return ya(a.toString(),b)};class Aa{constructor(){this.promise=new Promise(a=>{this.g=a})}};var Z=function(a="Devsite has failed to load."){throw Error(a);},Ca=async function(){var a=P;const b=new Aa;l("__devsiteAppReadyResolver",b.g);l("__devsiteAppReadyPromise",b.promise);l("DevsiteApp.whenReady",()=>b.promise);if(N(a.g,12).length)try{await Promise.all(N(a.g,12).map(f=>{f=sa(f);const g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",f.toString());return ya(f.toString(),g)}))}catch(f){Z(`Failed to load Devsite App dependencies: ${f.message}`)}const c=
d.DevsiteAppTenantCustomized?Q(a.g,6):Q(a.g,5);try{await za(`${c}${Ba(a)}`)}catch(f){if("en"!==a.g.getLocale()){M(a.g,2,"en");try{await za(`${c}${Q(a.g,4)}`)}catch(g){Z(`Failed to load Devsite App binary: ${g.message}`)}}else Z(`Failed to load Devsite App binary: ${f.message}`)}const e=document;if("complete"!==e.readyState&&"interactive"!==e.readyState){const f=new Aa;e.addEventListener("readystatechange",()=>{"interactive"!==e.readyState&&"complete"!==e.readyState||f.g()});await f.promise}},Ba=function(a){const b=
a.g.getLocale();a=Q(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const P=new class{constructor(){this.h=null;this.g=new da;this.i=[];this.j=a=>{this.i.push(a)};this.m=()=>{this.l()};if(d.__globalAppLoader)return d.__globalAppLoader;try{this.g=ea()}catch(a){Z("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;l("__globalAppLoader",this);l("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a))}l(){var a=document.querySelector("devsite-content");a&&(window.removeEventListener("message",this.j),a.removeEventListener("devsite-content-updated",this.m));
a=window;for(const b of this.i)a.dispatchEvent(b);this.i=[]}getEnv(){if(O(this.g,11))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){a:{var b=this.getEnv(),c=N(this.g,13),e=new URL(document.location.toString());e=new T(e.href);const f=Object.keys(q);if("PROD"!==b)for(const g of f)if(q[g]===
a&&(b=e.h.get(g),void 0!==b)){if("true"===b){a=!0;break a}if("false"===b){a=!1;break a}}a=Array.from(c).includes(a)}return a}},Da=document.querySelector("devsite-content");Da&&(window.addEventListener("message",P.j),Da.addEventListener("devsite-content-updated",P.l.bind(P)));
(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return P.h||(P.h=Ca()),P.h})().then(()=>{d.DevsiteAppInit||Z("Failed to load Devsite App binary");O(P.g,9)?DevsiteAppFrameboxInit(ca(),d.DevsiteAppAuthorizedElements):DevsiteAppInit(ca(),d.DevsiteAppAuthorizedElements)});}).call(this);
