(function(_ds){var window=this;var GN=function(){let a;a='<div class="devsite-code-buttons-container" role="group" aria-label="'+_ds.jC("Action buttons");return(0,_ds.T)(a+'"></div>')},HN=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')},IN=function(a){a=
a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')},JN=function(a){var b=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+
_ds.V(a.El)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.V(b)+'" data-title="'+_ds.V(b)+'"></button>')},KN=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(L){return L.replace(q,"&amp;").replace(r,"&lt;").replace(w,"&gt;")}function b(L,N,W){switch(L.nodeType){case 1:var K=L.tagName.toLowerCase();N.push("<",K);var sa=L.attributes,Ka=sa.length;if(Ka){if(W){for(var Na=[],Aa=Ka;0<=--Aa;)Na[Aa]=sa[Aa];Na.sort(function(xa,Ta){return xa.name<Ta.name?-1:xa.name===Ta.name?0:1});sa=Na}for(Aa=0;Aa<Ka;++Aa)Na=sa[Aa],Na.specified&&N.push(" ",Na.name.toLowerCase(),'="',Na.value.replace(q,"&amp;").replace(r,"&lt;").replace(w,"&gt;").replace(z,
"&quot;"),'"')}N.push(">");for(sa=L.firstChild;sa;sa=sa.nextSibling)b(sa,N,W);!L.firstChild&&/^(?:br|link|img)$/.test(K)||N.push("</",K,">");break;case 3:case 4:N.push(a(L.nodeValue))}}function c(L){function N(ca){if("\\"!==ca.charAt(0))return ca.charCodeAt(0);switch(ca.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(ca.substring(2),16)||ca.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(ca.substring(1),
8);default:return ca.charCodeAt(1)}}function W(ca){if(32>ca)return(16>ca?"\\x0":"\\x")+ca.toString(16);ca=String.fromCharCode(ca);if("\\"===ca||"-"===ca||"["===ca||"]"===ca)ca="\\"+ca;return ca}function K(ca){var ea=ca.substring(1,ca.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));ca=[];for(var Y=[],Fa="^"===ea[0],fa=Fa?1:0,Ba=ea.length;fa<Ba;++fa){var na=ea[fa];switch(na){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":ca.push(na);
continue}na=N(na);if(fa+2<Ba&&"-"===ea[fa+1]){var $a=N(ea[fa+2]);fa+=2}else $a=na;Y.push([na,$a]);65>$a||122<na||(65>$a||90<na||Y.push([Math.max(65,na)|32,Math.min($a,90)|32]),97>$a||122<na||Y.push([Math.max(97,na)&-33,Math.min($a,122)&-33]))}Y.sort(function(Wb,Vd){return Wb[0]-Vd[0]||Vd[1]-Wb[1]});ea=[];na=[NaN,NaN];for(fa=0;fa<Y.length;++fa)Ba=Y[fa],Ba[0]<=na[1]+1?na[1]=Math.max(na[1],Ba[1]):ea.push(na=Ba);Y=["["];Fa&&Y.push("^");Y.push.apply(Y,ca);for(fa=0;fa<ea.length;++fa)Ba=ea[fa],Y.push(W(Ba[0])),
Ba[1]>Ba[0]&&(Ba[1]+1>Ba[0]&&Y.push("-"),Y.push(W(Ba[1])));Y.push("]");return Y.join("")}function sa(ca){for(var ea=ca.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),Y=ea.length,Fa=[],fa=0,Ba=0;fa<Y;++fa){var na=ea[fa];"("===na?++Ba:"\\"===na.charAt(0)&&(na=+na.substring(1))&&na<=Ba&&(Fa[na]=-1)}for(fa=1;fa<Fa.length;++fa)-1===Fa[fa]&&(Fa[fa]=++Ka);for(Ba=fa=0;fa<
Y;++fa)na=ea[fa],"("===na?(++Ba,void 0===Fa[Ba]&&(ea[fa]="(?:")):"\\"===na.charAt(0)&&(na=+na.substring(1))&&na<=Ba&&(ea[fa]="\\"+Fa[Ba]);for(Ba=fa=0;fa<Y;++fa)"^"===ea[fa]&&"^"!==ea[fa+1]&&(ea[fa]="");if(ca.ignoreCase&&Na)for(fa=0;fa<Y;++fa)na=ea[fa],ca=na.charAt(0),2<=na.length&&"["===ca?ea[fa]=K(na):"\\"!==ca&&(ea[fa]=na.replace(/[a-zA-Z]/g,function($a){$a=$a.charCodeAt(0);return"["+String.fromCharCode($a&-33,$a|32)+"]"}));return ea.join("")}for(var Ka=0,Na=!1,Aa=!1,xa=0,Ta=L.length;xa<Ta;++xa){var Ua=
L[xa];if(Ua.ignoreCase)Aa=!0;else if(/[a-z]/i.test(Ua.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Na=!0;Aa=!1;break}}var Ia=[];xa=0;for(Ta=L.length;xa<Ta;++xa){Ua=L[xa];if(Ua.global||Ua.multiline)throw Error(""+Ua);Ia.push("(?:"+sa(Ua)+")")}return new RegExp(Ia.join("|"),Aa?"gi":"g")}function d(L){var N=0;return function(W){for(var K=null,sa=0,Ka=0,Na=W.length;Ka<Na;++Ka)switch(W.charAt(Ka)){case "\t":K||(K=[]);K.push(W.substring(sa,Ka));sa=L-N%L;for(N+=sa;0<=sa;sa-=16)K.push("                ".substring(0,
sa));sa=Ka+1;break;case "\n":N=0;break;default:++N}if(!K)return W;K.push(W.substring(sa));return K.join("")}}function e(L,N,W,K){N&&(L={source:N,Sh:L},W(L),K.push.apply(K,L.ai))}function f(L,N){var W={},K;(function(){for(var Na=L.concat(N),Aa=[],xa={},Ta=0,Ua=Na.length;Ta<Ua;++Ta){var Ia=Na[Ta],ca=Ia[3];if(ca)for(var ea=ca.length;0<=--ea;)W[ca.charAt(ea)]=Ia;Ia=Ia[1];ca=""+Ia;xa.hasOwnProperty(ca)||(Aa.push(Ia),xa[ca]=null)}Aa.push(/[\0-\uffff]/);K=c(Aa)})();var sa=N.length,Ka=function(Na){for(var Aa=
Na.Sh,xa=[Aa,"pln"],Ta=0,Ua=Na.source.match(K)||[],Ia={},ca=0,ea=Ua.length;ca<ea;++ca){var Y=Ua[ca],Fa=Ia[Y],fa=void 0;if("string"===typeof Fa)var Ba=!1;else{var na=W[Y.charAt(0)];if(na)fa=Y.match(na[1]),Fa=na[0];else{for(Ba=0;Ba<sa;++Ba)if(na=N[Ba],fa=Y.match(na[1])){Fa=na[0];break}fa||(Fa="pln")}!(Ba=5<=Fa.length&&"lang-"===Fa.substring(0,5))||fa&&"string"===typeof fa[1]||(Ba=!1,Fa="src");Ba||(Ia[Y]=Fa)}na=Ta;Ta+=Y.length;if(Ba){Ba=fa[1];var $a=Y.indexOf(Ba),Wb=$a+Ba.length;fa[2]&&(Wb=Y.length-
fa[2].length,$a=Wb-Ba.length);Fa=Fa.substring(5);e(Aa+na,Y.substring(0,$a),Ka,xa);e(Aa+na+$a,Ba,l(Fa,Ba),xa);e(Aa+na+Wb,Y.substring(Wb),Ka,xa)}else xa.push(Aa+na,Fa)}Na.ai=xa};return Ka}function g(L){var N=[],W=[];L.tripleQuotedStrings?N.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):L.multiLineStrings?N.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):N.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);L.verbatimStrings&&W.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var K=L.hashComments;K&&(L.cStyleComments?(1<K?N.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):N.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),W.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):N.push(["com",
/^#[^\r\n]*/,null,"#"]));L.cStyleComments&&(W.push(["com",/^\/\/[^\r\n]*/,null]),W.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));L.regexLiterals&&W.push(["lang-regex",new RegExp("^"+n+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);L=L.keywords.replace(/^\s+|\s+$/g,"");L.length&&W.push(["kwd",new RegExp("^(?:"+L.replace(/\s+/g,"|")+")\\b"),null]);N.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);W.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,
null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(N,W)}function h(L){function N(Re){if(Re>xa){Ta&&Ta!==Ua&&(Aa.push("</span>"),Ta=null);!Ta&&Ua&&(Ta=Ua,Aa.push('<span class="',Ta,'">'));var El=a(ea(W.substring(xa,Re))).replace(na?Fa:Y,"$1&#160;");na=Ba.test(El);Aa.push(El.replace(fa,Dl));xa=Re}}var W=L.source,K=L.Vl,sa=L.ai,Ka=L.Li,Na=L.aj,
Aa=[],xa=0,Ta=null,Ua=null,Ia=0,ca=0,ea=d(window.PR_TAB_WIDTH),Y=/([\r\n ]) /g,Fa=/(^| ) /gm,fa=/\r\n?|\n/g,Ba=/[ \r\n]$/,na=!0,$a=window._pr_isIE6();Na=$a?Na&&"PRE"===Na.tagName?6===$a?"&#160;\r\n":7===$a?"&#160;<br />\r":8===$a?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Ka){var Wb=[];for($a=0;10>$a;++$a)Wb[$a]=Na+'</li><li class="L'+$a+'">';var Vd="number"===typeof Ka?Ka-1:0;Aa.push('<ol class="linenums"><li class="L',Vd%10,'"');Vd&&Aa.push(' value="',Vd+1,'"');Aa.push(">");var Dl=function(){var Re=
Wb[++Vd%10];return Ta?"</span>"+Re+'<span class="'+Ta+'">':Re}}else Dl=Na;for(;;)if(Ia<K.length&&(ca<sa.length?K[Ia]<=sa[ca]:1))N(K[Ia]),Ta&&(Aa.push("</span>"),Ta=null),Aa.push(K[Ia+1]),Ia+=2;else if(ca<sa.length)N(sa[ca]),Ua=sa[ca+1],ca+=2;else break;N(W.length);Ta&&Aa.push("</span>");Ka&&Aa.push("</li></ol>");L.Mg=Aa.join("")}function k(L,N){for(var W=N.length;0<=--W;){var K=N[W];Oa.hasOwnProperty(K)?"console"in window&&console.warn("cannot override language handler %s",K):Oa[K]=L}}function l(L,
N){L&&Oa.hasOwnProperty(L)||(L=/^\s*</.test(N)?"default-markup":"default-code");return Oa[L]}function m(L){var N=L.$i,W=L.Di;L.Mg=N;try{var K=N.match(ab);N=[];var sa=0,Ka=[];if(K)for(var Na=0,Aa=K.length;Na<Aa;++Na){var xa=K[Na];if(1<xa.length&&"<"===xa.charAt(0)){if(!La.test(xa))if(wa.test(xa))N.push(xa.substring(9,xa.length-3)),sa+=xa.length-12;else if(qb.test(xa))N.push("\n"),++sa;else if(0<=xa.indexOf("nocode")&&xa.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Ta=
xa.match(Ha)[2],Ua=1;var Ia=Na+1;a:for(;Ia<Aa;++Ia){var ca=K[Ia].match(Ha);if(ca&&ca[2]===Ta)if("/"===ca[1]){if(0===--Ua)break a}else++Ua}Ia<Aa?(Ka.push(sa,K.slice(Na,Ia+1).join("")),Na=Ia):Ka.push(sa,xa)}else Ka.push(sa,xa)}else{Ua=xa;var ea=Ua.indexOf("&");if(0>ea)var Y=Ua;else{for(--ea;0<=(ea=Ua.indexOf("&#",ea+1));){var Fa=Ua.indexOf(";",ea);if(0<=Fa){var fa=Ua.substring(ea+3,Fa),Ba=10;fa&&"x"===fa.charAt(0)&&(fa=fa.substring(1),Ba=16);var na=parseInt(fa,Ba);isNaN(na)||(Ua=Ua.substring(0,ea)+
String.fromCharCode(na)+Ua.substring(Fa+1))}}Y=Ua.replace(y,"<").replace(C,">").replace(A,"'").replace(O,'"').replace(S," ").replace(ha,"&")}N.push(Y);sa+=Y.length}}var $a=N.join("");L.source=$a;L.Sh=0;L.Vl=Ka;l(W,$a)(L);h(L)}catch(Wb){"console"in window&&console.log(Wb&&Wb.stack?Wb.stack:Wb)}}var n=function(){for(var L="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
N="(?:^^|[+-]",W=0;W<L.length;++W)N+="|"+L[W].replace(/([^=<>:&a-z])/g,"\\$1");return N+")\\s*"}(),q=/&/g,r=/</g,w=/>/g,z=/"/g,y=/&lt;/g,C=/&gt;/g,A=/&apos;/g,O=/&quot;/g,ha=/&amp;/g,S=/&nbsp;/g,ma=/[\r\n]/g,Ja=null,ab=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),La=/^\x3c!--/,wa=/^<!\[CDATA\[/,qb=/^<br\b/i,Ha=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,yb=g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Oa={};k(yb,["default-code"]);k(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));k(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);k(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));k(g({keywords:"null true false"}),["json"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);k(g({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);k(g({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);k(g({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);k(g({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);k(g({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);k(g({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);k(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(L,N,W){L={$i:L,Di:N,Li:W};m(L);return L.Mg};window.prettyPrint=function(L){function N(){for(var Ua=
window.PR_SHOULD_USE_CONTINUATION?Aa.now()+250:Infinity;xa<K.length&&Aa.now()<Ua;xa++){var Ia=K[xa];if(Ia.className&&0<=Ia.className.indexOf("prettyprint")){var ca=Ia.className.match(/\blang-(\w+)\b/);ca&&(ca=ca[1]);for(var ea=!1,Y=Ia.parentNode;Y;Y=Y.parentNode)if(("pre"===Y.tagName||"code"===Y.tagName||"xmp"===Y.tagName)&&Y.className&&0<=Y.className.indexOf("prettyprint")){ea=!0;break}if(!ea){Y=Ia;null===Ja&&(ea=document.createElement("PRE"),ea.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
Ja=!/</.test(ea.innerHTML));if(Ja)if(ea=Y.innerHTML,"XMP"===Y.tagName)ea=a(ea);else{if("PRE"!==Y.tagName&&ma.test(ea)){var Fa="";Y.currentStyle?Fa=Y.currentStyle.whiteSpace:window.getComputedStyle&&(Fa=window.getComputedStyle(Y,null).whiteSpace);Y=!Fa||"pre"===Fa}else Y=!0;Y||(ea=ea.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{ea=[];for(Y=Y.firstChild;Y;Y=Y.nextSibling)b(Y,ea);ea=ea.join("")}ea=ea.replace(/(?:\r\n?|\n)$/,"");Y=Ia.className.match(/\blinenums\b(?::(\d+))?/);
Ta={$i:ea,Di:ca,aj:Ia,Li:Y?Y[1]&&Y[1].length?+Y[1]:!0:!1};m(Ta);if(Ia=Ta.Mg)if(ca=Ta.aj,"XMP"===ca.tagName){ea=document.createElement("PRE");for(Y=0;Y<ca.attributes.length;++Y)Fa=ca.attributes[Y],Fa.specified&&("class"===Fa.name.toLowerCase()?ea.className=Fa.value:ea.setAttribute(Fa.name,Fa.value));ea.innerHTML=Ia;ca.parentNode.replaceChild(ea,ca)}else ca.innerHTML=Ia}}}xa<K.length?setTimeout(N,250):L&&L()}for(var W=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],
K=[],sa=0;sa<W.length;++sa)for(var Ka=0,Na=W[sa].length;Ka<Na;++Ka)K.push(W[sa][Ka]);W=null;var Aa=Date;Aa.now||(Aa={now:function(){return(new Date).getTime()}});var xa=0,Ta;N()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:k,sourceDecorator:g,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);var LN=window;var NN=function(a){a.D&&a.eventHandler.listen(a.D,"click",()=>void a.setAttribute("dark-code",""));a.F&&a.eventHandler.listen(a.F,"click",()=>void a.removeAttribute("dark-code"));a.j&&a.eventHandler.listen(a.j,"click",()=>void MN(a));a.v&&a.eventHandler.listen(a.v,"click",()=>{const b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.vH(c,b):_ds.uH([a],b)})},MN=async function(a){var b,c=a.querySelector("pre:not(.devsite-copy-hide)");
if(c&&(c=[...c.childNodes],_ds.bq(document.body,c),a.C)){const d=new _ds.vk;null===(b=a.j)||void 0===b?void 0:b.setAttribute("aria-label","Code sample copied to clipboard");_ds.tk(a.eventHandler,a.C,"transitionend",()=>{d.h()});await d.promise;_ds.tk(a.eventHandler,a.C,"transitionend",()=>{var e;null===(e=a.j)||void 0===e?void 0:e.setAttribute("aria-label",a.G)})}},ON=class extends _ds.D{constructor(){super(["devsite-snackbar"]);this.C=this.F=this.v=this.D=this.j=this.h=null;this.K=!1;this.G="";this.eventHandler=
new _ds.F;this.J=new _ds.vk;this.H=new _ds.bm;this.L=new _ds.tE(_ds.xE(_ds.wE()));_ds.Jg(this,(0,_ds.Pb)`no-toggle`)}static get observedAttributes(){return["dark-code"]}whenReady(){return this.J.promise}async connectedCallback(){var a=await _ds.v();if(!this.K){var b=this.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))this.setAttribute("no-copy",
""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");this.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");var c=b.getAttribute("data-label");this.G=c?`${"Copy code sample"}: ${c}`:"Copy code sample";b.classList.contains("devsite-disable-code-toggle")&&(_ds.B(this,"no-toggle","",this),b.classList.remove("devsite-disable-code-toggle"))}if(b=this.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample"))this.setAttribute("js-fiddle",
""),b.classList.remove("devsite-enable-open-in-jsfiddle"),b.classList.add("devsite-jsfiddle-code-sample");if(this.hasAttribute("js-fiddle")&&b){c=["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"];for(var d of c)b.hasAttribute(`data-${d}`)&&(this.setAttribute(d,`${b.getAttribute(`data-${d}`)}`),b.removeAttribute(`data-${d}`))}this.prettyPrint();this.K=!0}if((d=this.querySelector(".devsite-dark-code-default"))||this.H.get("pref_dark-code"))this.setAttribute("dark-code",""),d&&d.classList.remove("devsite-dark-code-default");
this.J.h();try{await a.intersectionEnterForElement(this)}catch(k){if("IntersectionObserver not supported"!==k.message)return}if(a=this.querySelector(".devsite-code-buttons-container"))this.h=a;else{this.h=_ds.P(GN);var e,f,g,h;this.hasAttribute("scope")&&(this.v=_ds.P(KN,{label:"Open code sample in JSFiddle"}),(this.hasAttribute("jsfiddle-label")||this.hasAttribute("jsfiddle-title"))&&this.v.setAttribute("data-label",`${this.getAttribute("jsfiddle-label")||this.getAttribute("jsfiddle-title")}`),null===
(e=this.h)||void 0===e?void 0:e.appendChild(this.v));this.hasAttribute("no-toggle")||(this.D=_ds.P(HN,{label:"Dark code theme"}),null===(f=this.h)||void 0===f?void 0:f.appendChild(this.D),this.F=_ds.P(IN,{label:"Light code theme"}),null===(g=this.h)||void 0===g?void 0:g.appendChild(this.F));this.hasAttribute("no-copy")||(e=this.getAttribute("data-copy-event-label"),f="Click To Copy",e&&(f+=`: ${e}`),this.j=_ds.P(JN,{label:this.G,El:f}),null===(h=this.h)||void 0===h?void 0:h.appendChild(this.j));this.prepend(this.h)}NN(this);
this.C=document.querySelector("devsite-snackbar")}async disconnectedCallback(){(await _ds.v()).unregisterIntersectionForElement(this);this.h&&this.removeChild(this.h);_ds.G(this.eventHandler)}prettyPrint(){var a=[...this.getElementsByClassName("prettyprint")];for(const c of a){c.classList.remove("prettyprint");a=(a=c.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?a[1]:void 0;var b=a;a=c.innerHTML;b=null!==b&&void 0!==b?b:"";a=a.replace(/(&#39;)/g,"'");a=LN.prettyPrintOne(a,b,void 0);_ds.Dc(c,
this.L.h(a));c.getElementsByTagName("strong").length&&c.classList.add("devsite-code-highlight")}}async attributeChangedCallback(a,b,c){if("dark-code"===a&&b!==c&&!this.querySelector(".devsite-dark-code-default"))if(this.hasAttribute("dark-code")){this.H.set("pref_dark-code","1");await _ds.gj();var d=[...document.querySelectorAll("devsite-code:not([dark-code])")].filter(f=>f!==this);for(var e of d)e.setAttribute("dark-code","")}else{this.H.remove("pref_dark-code");await _ds.gj();e=[...document.querySelectorAll("devsite-code[dark-code]")];
for(d of e)d.removeAttribute("dark-code")}}};ON.prototype.attributeChangedCallback=ON.prototype.attributeChangedCallback;ON.prototype.disconnectedCallback=ON.prototype.disconnectedCallback;ON.prototype.connectedCallback=ON.prototype.connectedCallback;ON.prototype.whenReady=ON.prototype.whenReady;try{window.customElements.define("devsite-code",ON)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
