(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var uT=_ds.Xg(function(){return!_ds.yd||0<=_ds.ta(_ds.EH,9)}),vT=_ds.Xg(function(){return _ds.Cd||_ds.zd||_ds.Bd&&0<=_ds.ta(_ds.EH,10)||_ds.yd&&0<=_ds.ta(_ds.EH,10)}),xT=function(a,b){uT()&&(b=vT()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.zk(a,wT(),b))},wT=_ds.Xg(function(){return _ds.yd&&9==_ds.Td?"-ms-transform":"transform"});var AT=function(a){a.j=yT(a,".devsite-top-logo-row-wrapper-wrapper");a.h=yT(a,".devsite-collapsible-section");a.v=yT(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);zT(a)},zT=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.H&&(_ds.zk(b,"transform",`translate3d(0, -${a.offset}px, 0)`),BT(a),a.H=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},CT=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.G(a.F);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.ih(b.offsetWidth,b.offsetHeight);b=new _ds.ih(c.offsetWidth,c.offsetHeight);var f=_ds.Sk(c,"margin"),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.zk(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});xT(c,a.hasAttribute("search-active")?0:e);_ds.tk(a.F,d,_ds.Le,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),xT(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");if(uT()){var m=vT()?"scale3d("+l+",1,1)":"scale("+l+",1)";_ds.zk(d,wT(),m)}xT(c,k)})}},DT=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null===a||void 0===a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.gj(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},FT=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.X;_ds.ci(b.target,null,"devsite-top-logo-row-middle",void 0)&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>ET(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{ET(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},GT=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},BT=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},ET=function(a){window.requestAnimationFrame(()=>
a.K.xa())},yT=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},HT=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},IT=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Mg(a,c,b))},JT=class extends _ds.D{constructor(){super(...arguments);this.eventHandler=new _ds.F;this.H=
-1;this.F=new _ds.F;this.D=0;this.G=new MutationObserver(()=>AT(this));this.K=new _ds.pk(()=>{AT(this);BT(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.j=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;zT(this);break;case "search-active":CT(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),DT(this,a)}}connectedCallback(){FT(this);GT(this);BT(this);AT(this);this.G.observe(this,{childList:!0,subtree:!0});zT(this);const a=_ds.E();this.authUser=_ds.Hi(_ds.Ji(a.href),"authuser")}disconnectedCallback(){_ds.G(this.eventHandler);this.G.disconnect()}C(){return this.j+this.h-this.offset}J(){return this.j+this.h}Ta(a){this.updated=!1;if(a){IT(this,a,".devsite-header-upper-tabs");
IT(this,a,".devsite-collapsible-section");IT(this,a,".devsite-product-name-wrapper");IT(this,a,"devsite-language-selector");IT(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&HT(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(HT(c,b),c=_ds.E(),c=_ds.Hi(_ds.Ji(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Mg(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Mg(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Kh(this),this.appendChild(a));GT(this);ET(this)}};try{window.customElements.define("devsite-header",JT)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
