(function(_ds){var window=this;var RY=["track-type","track-name","track-metadata-eventdetail","track-metadata-position"],TY=function(a){var b=[...a.children];for(var c of b)if(c.matches(".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample")){(b=c.getAttribute("data-ds-scope"))&&_ds.B(a,"scope",b,a);b=".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample".split(/[,.]/).filter(e=>e.length);const d=[...c.classList];for(const e of d)b.includes(e)||a.classList.add(e);for(c.hasAttribute("no-overflow")&&_ds.B(a,
"no-overflow","",a);c.childNodes.length;)a.appendChild(c.childNodes[0]);c.remove()}c=a.querySelectorAll(".kd-tabbed-horz,.kd-tabbed-vert");for(const d of c)d.matches(".kd-tabbed-horz,.kd-tabbed-vert")&&SY(a,d)},UY=function(a){var b;a.h=!0;var c=a.getAttribute("scope"),d=null,e=_ds.E().searchParams.get("tab");e&&(d=_ds.jj(e));d||a.hasAttribute("no-pref")||(d=a.j.get(`pref_ds_${c}`));c=a.ownerDocument.createElement("devsite-tabs");_ds.B(a,"role","tablist",c);a.hasAttribute("no-overflow")&&_ds.B(a,"no-overflow",
"",c);a.zb=c;e=[...a.children].filter(m=>m.matches("section"));for(var f of e){e=a.ownerDocument.createElement("tab");const m=a.ownerDocument.createElement("a");f.querySelector(".two-line-tab")&&_ds.B(a,"two-line","",e);_ds.B(a,"role","tab",e);_ds.B(a,"aria-selected","false",e);const n=f.querySelector("h1,h2,h3,h4,h5,h6");var g="";let q="";if(n&&""!==(null===(b=n.textContent)||void 0===b?void 0:b.trim())){g="";n.id&&(q=n.id);var h=n.querySelector(".firebase-platform-label");if(null===h||void 0===
h?0:h.textContent)g=h.textContent.trim(),h.remove();h=n.textContent||"";var k=f.querySelector("[tab-label]");if(null===k||void 0===k?0:k.hasAttribute("tab-label"))g=`${k.getAttribute("tab-label")}`;n.remove();g?(k=a.ownerDocument.createElement("span"),_ds.B(a,"tab-label",g,k),k.textContent=h.trim(),m.appendChild(k),g=_ds.jj(`${h} ${g}`)):(m.append(...n.childNodes),g=_ds.jj(null!==h&&void 0!==h?h:"")||"tab");_ds.B(a,"aria-controls",`tabpanel-${g}`,e);m.id=`aria-tab-${g}`;_ds.B(a,"role","button",m);
if(n.hasAttributes())for(var l of RY)h=n.getAttribute(l),null!==h&&_ds.B(a,l,h,m)}else g="Error",n&&(g=n.getAttribute("data-text")||"Error"),m.textContent=g,g=_ds.jj(g);_ds.Ac(m,_ds.fc(`#${g}`));e.appendChild(m);c.querySelector(`[${"tab"}="${g}"]`)||(_ds.B(a,"tab",g,e),q&&(e.id=q),c.appendChild(e));_ds.B(a,"tab",g,f);_ds.B(a,"role","tabpanel",f);_ds.B(a,"aria-labelledby",`aria-tab-${g}`,f);_ds.B(a,"tabindex","0",f);f.id=`tabpanel-${g}`}_ds.Lh(a,c,0);f=_ds.E().hash.substring(1);e=[...a.children];l=
c.querySelector(`tab[id="${f}"]`);(e=e.find(m=>m.matches(".selected")))&&e.classList.remove("selected");f&&l?_ds.B(a,"active",`${l.getAttribute("tab")}`,a):d&&c.querySelector(`[${"tab"}="${d}"]`)?_ds.B(a,"tab-to-select",d,a):e?_ds.B(a,"active",`${e.getAttribute("tab")}`,a):a.hasAttribute("active")||(d=c.querySelector("[tab]"),_ds.B(a,"active",`${null===d||void 0===d?void 0:d.getAttribute("tab")}`,a));_ds.B(a,"ready","",a)},VY=function(a){a.zb&&a.eventHandler.listen(a.zb,"click",b=>{if(!b.defaultPrevented){b.preventDefault();
b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));b=b.target;for(var c;!c&&b&&b!==a;)"TAB"===(null===b||void 0===b?void 0:b.tagName.toUpperCase())&&(c=b),b=null===b||void 0===b?void 0:b.parentElement;if(null===c||void 0===c?0:c.hasAttribute("tab")){c=`${c.getAttribute("tab")}`;b=a.getBoundingClientRect();a.dispatchEvent(new CustomEvent("devsite-sticky-freeze",{bubbles:!0}));const f=a.getAttribute("scope");var d=[...a.ownerDocument.querySelectorAll(`${"devsite-selector"}[${"scope"}="${f}"]`+
`:not([${"active"}="${c}"])`)];for(var e of d)e!==a&&_ds.B(a,"tab-to-select",c,e);_ds.B(a,"active",c,a);e=a.getBoundingClientRect();d=_ds.Eh(document);window.scrollTo(d.x,d.y+e.top-b.top);a.hasAttribute("no-pref")||a.j.set(`pref_ds_${f}`,c);e=a.querySelector(`:scope > devsite-tabs [${"tab"}="${c}"]`);(null===e||void 0===e?0:e.id)&&_ds.Ui(`#${e.id}`,!0);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}}})},SY=function(a,b){var c=[...b.children];for(const d of c)if(d.matches("article")){c=
a.ownerDocument.createElement("section");for(d.classList.contains("selected")&&c.classList.add("selected");d.childNodes.length;)c.appendChild(d.childNodes[0]);const e=c.querySelector("header");if(e){const f=a.ownerDocument.createElement("h3");e.childNodes.length&&f.append(...e.childNodes);f.id=e.id;_ds.Nh(f,e)}a.appendChild(c);d.remove()}b.remove()},WY=class extends _ds.D{constructor(){super(["devsite-tabs"]);this.eventHandler=new _ds.F;this.j=new _ds.bm;this.h=!1;this.zb=null;_ds.Jg(this,(0,_ds.Pb)`no-overflow`,
(0,_ds.Pb)`ready`,(0,_ds.Pb)`role`,(0,_ds.Pb)`scope`,(0,_ds.Pb)`tab`,(0,_ds.Pb)`tab-to-select`,(0,_ds.Pb)`no-pref`,(0,_ds.Pb)`two-line`,(0,_ds.Pb)`tab-label`,(0,_ds.Pb)`aria-selected`,(0,_ds.Pb)`aria-controls`,(0,_ds.Pb)`aria-labelledby`,(0,_ds.Pb)`active`,(0,_ds.Pb)`track-type`,(0,_ds.Pb)`track-name`,(0,_ds.Pb)`track-metadata-eventDetail`,(0,_ds.Pb)`track-metadata-position`,(0,_ds.Pb)`track-metadata-end-goal`)}static get observedAttributes(){return["active","tab-to-select"]}connectedCallback(){TY(this);
this.getAttribute("scope")||_ds.B(this,"scope","auto",this);this.h||UY(this);VY(this)}disconnectedCallback(){_ds.G(this.eventHandler)}attributeChangedCallback(a,b,c){const d=[];var e=[...this.children];for(const g of e)if(g.matches(`section[${"tab"}="${c}"]`))d.push(g);else if(g.matches("devsite-tabs")){const h=g.querySelector(`tab[${"tab"}="${c}"]`);h&&d.push(h)}if("active"===a&&c)if(d.length){for(var f of e)f.matches("section[tab][active]")?f.removeAttribute("active"):f.matches("devsite-tabs")&&
(b=f.querySelector("tab[tab][active]"))&&(b.removeAttribute("active"),_ds.B(this,"aria-selected","false",b),(b=f.querySelector("a[aria-selected=true]"))&&b.removeAttribute("aria-selected"));for(const g of d)_ds.B(this,"active","",g),g.matches("tab")&&(_ds.B(this,"aria-selected","true",g),(f=g.querySelector("a"))&&_ds.B(this,"aria-selected","true",f))}else b&&_ds.B(this,a,b,this);if("tab-to-select"===a&&c){if(d.length)_ds.B(this,"active",c,this);else{a=this.getAttribute("active");for(const g of e)g.matches("devsite-tabs")&&
(e=g.querySelector(`tab[${"tab"}="${a}"]`))&&_ds.B(this,"active",`${e.getAttribute("tab")}`,this)}this.removeAttribute("tab-to-select")}}};WY.prototype.attributeChangedCallback=WY.prototype.attributeChangedCallback;WY.prototype.disconnectedCallback=WY.prototype.disconnectedCallback;WY.prototype.connectedCallback=WY.prototype.connectedCallback;try{window.customElements.define("devsite-selector",WY)}catch(a){console.warn("devsite.app.customElement.DevsiteSelector",a)};})(_ds_www);
