(function(_ds){var window=this;var vM=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},wM=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},xM=function(a){var b=a.Tm;a='<span class="devsite-nav-filter-match-count"> (<mark>';b=_ds.mx(new _ds.ix("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:b,XXX_1:_ds.U(_ds.Hp(1)),XXX_2:_ds.U(_ds.Hp(b))});
return(0,_ds.T)(a+b+"</mark>)</span>")};var yM="onpointerover"in window?"pointerover":"mouseover",zM=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.B(a,"visually-hidden","",c))},GM=function(a){a.eventHandler.listen(a,"click",b=>{var c;if(!b.defaultPrevented){const e=b.target;"devsite-close-nav"===e.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0})):_ds.B(a,"top-level-nav",""));if(e.hasAttribute("menu")){const f=e.getAttribute("menu");f&&AM(a,f)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(e.classList.contains("devsite-nav-toggle")||e.classList.contains("devsite-nav-title-no-path")||(null===(c=e.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.v&&(b=a.v.querySelector("[menu=_book]"))&&b.contains(e)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",
{bubbles:!0}));var d;e instanceof Element&&e.matches("a.devsite-nav-title")?d=e:d=_ds.ci(e,"a","devsite-nav-title");d&&!d.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[yM,"focusin"],b=>void BM(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.v&&(AM(a,"_book")?a.removeAttribute("top-level-nav"):_ds.B(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.L.xa());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.L.xa()});a.eventHandler.listen(a,"scroll",()=>{_ds.B(a,"user-scrolled","")});a.eventHandler.listen(a.h,"click",()=>{CM(a)});a.j&&a.K.length&&(a.eventHandler.listen(a.j,"keyup",()=>{var b,c,d,e,f,g,h,k;DM(a);EM(a);const l=null===(c=null===(b=a.j)||void 0===b?void 0:b.value)||void 0===c?void 0:c.trim().toLowerCase();if(l){null===(d=a.H)||void 0===d?void 0:d.classList.remove("hidden");for(const n of a.K){d=n.querySelectorAll(".devsite-nav-text");
c=n.classList.contains("devsite-nav-expandable");var m=e=!1;b=0;if(l&&c&&(null===(g=null===(f=n.querySelector(".devsite-nav-text"))||void 0===f?void 0:f.textContent)||void 0===g?0:g.toLowerCase().includes(l)))m=e=!0;else for(const q of d)l&&(null===(h=q.textContent)||void 0===h?0:h.toLowerCase().includes(l))&&(e=!0,++b);if(!0===e){n.classList.remove("hidden");if(m){d=Array.from(n.querySelectorAll(".devsite-nav-item"));for(const q of d)q.classList.remove("hidden"),l&&(null===(k=q.textContent)||void 0===
k?0:k.toLowerCase().includes(l))&&++b}d=void 0;(m=n.querySelector(".devsite-nav-text"))&&(e=null===(d=m.textContent)||void 0===d?void 0:d.replace(new RegExp(`(${l})`,"ig"),"<mark>$1</mark>"))&&_ds.Dc(m,_ds.Nf.h(e))}c&&0<b&&(c=n.querySelector(".devsite-nav-text"))&&(b=_ds.P(xM,{Tm:b}),c.appendChild(b))}}else null===(e=a.H)||void 0===e?void 0:e.classList.add("hidden")}),a.eventHandler.listen(a.j,"focus",()=>void FM(a,"focus")));a.H&&a.eventHandler.listen(a.H,"click",()=>{var b;a.j&&(a.j.value="");null===
(b=a.H)||void 0===b?void 0:b.classList.add("hidden");DM(a);EM(a);FM(a,"click")})},IM=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.F=new Set(b);if(!_ds.E().hash&&c)HM(a,a.F);else{c=new _ds.vF;for(const d of a.F)_ds.uF(c,d)}},JM=async function(a){const b=await _ds.v();for(const c of a.F)b.unregisterIntersectionForElement(c)},KM=function(a){a.K=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},
DM=function(a){var b;for(const c of a.K)c.classList.toggle("hidden",!(null===(b=a.j)||void 0===b||!b.value))},EM=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a)a=c.parentElement,b=null===a||void 0===a?void 0:a.textContent,a&&b&&_ds.Dc(a,_ds.Nf.h(b))}},HM=async function(a,b){if(a.D){var c=await _ds.v(),d=new _ds.vF,e=f=>{f=
f.target;_ds.uF(d,f);a.F.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},BM=function(a,b){b.defaultPrevented||(b=_ds.bi(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Ac(b,_ds.fc(_ds.$i(b.href).href)))},CM=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:0;_ds.tk(a.eventHandler,
a,_ds.Le,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.C.removeAttribute("animatable")});_ds.B(a,"animatable","");b=_ds.Fc(a.o`animatable`);b(a.background,"animatable","");b(a.C,"animatable","");a.hasAttribute("collapsed")?(_ds.B(a,"aria-expanded","true",a.h),_ds.B(a,"aria-label","Hide side navigation",a.h),_ds.B(a,"data-title","Hide side navigation",a.h),a.removeAttribute("collapsed"),LM(a,"Expanded book nav")):(a.h.removeAttribute("aria-expanded"),_ds.B(a,"aria-label",
"Show side navigation",a.h),_ds.B(a,"data-title","Show side navigation",a.h),_ds.B(a,"collapsed",""),LM(a,"Collapsed book nav"));await _ds.gj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},FM=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},
bubbles:!0}))},AM=function(a,b){let c=!1;if(a.v)for(const d of a.v.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.B(a,"hidden","",d);return c},MM=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.mj(_ds.E().pathname);a=`[href="${_ds.$i(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},NM=function(a,b=a){b||(b=a);const c=b.querySelector(".devsite-mobile-nav-bottom");if(c){let d=c.querySelector(".devsite-nav-active");for(;d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.tk(a.eventHandler,d,"devsite-expandable-nav-transition-end",()=>{d&&_ds.B(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement}},PM=
async function(a){a.D&&(a.removeAttribute("user-scrolled"),await _ds.gj(),await OM(a),await a.O,await _ds.v(),await _ds.gj(),await OM(a))},OM=async function(a){if(a.D&&a.v){await _ds.v();var b=a.v.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await QM(a,b))}},QM=async function(a,b){if(a.D){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Jk(b,a,!0).y;await _ds.gj();c&&_ds.B(a,"user-scrolled","")}},LM=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},RM=class extends _ds.D{constructor(){super();this.D=!1;this.H=this.j=this.G=this.v=null;this.K=[];this.eventHandler=new _ds.F;this.R=()=>{};this.F=new Set;this.J=this.M=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.h=_ds.P(vM);this.C=_ds.P(wM);this.O=new Promise(a=>{this.R=a});this.L=new _ds.pk(()=>{this.D&&zM(this)},20)}static get observedAttributes(){return["collapsed",
"fixed","hidden"]}async connectedCallback(){var a,b;this.D=!0;_ds.Jg(this,this.o`animatable`,this.o`aria-expanded`,this.o`aria-label`,this.o`collapsed`,this.o`data-title`,this.o`fixed`,this.o`has-book-nav`,this.o`hidden`,this.o`role`,this.o`top-level-nav`,this.o`user-scrolled`,this.o`visually-hidden`);_ds.B(this,"role","menu");this.parentNode&&this.parentNode.insertBefore(this.background,this);this.hasAttribute("hidden")&&(_ds.B(this,"hidden","",this.h),_ds.B(this,"hidden","",this.C));const c=await _ds.v();
if(this.M=c.hasFlagAccess(150))null===(a=this.parentElement)||void 0===a?void 0:a.insertBefore(this.h,this.nextSibling),_ds.B(this,"aria-label","Hide side navigation",this.h),_ds.B(this,"data-title","Hide side navigation",this.h),_ds.B(this,"aria-expanded","true",this.h),null===(b=this.parentElement)||void 0===b?void 0:b.insertBefore(this.C,this.nextSibling);if(this.J=c.hasFlagAccess(155))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.j=this.G.querySelector("input[type=text]"),this.H=
this.G.querySelector(".filter-clear-button"),KM(this);zM(this);GM(this);await this.init();IM(this)}disconnectedCallback(){this.D=!1;_ds.G(this.eventHandler);JM(this);this.F.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.B(this,"visually-hidden","",a);a=[this.background,this.h,this.C];for(const b of a)b&&_ds.Mh(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.C.removeAttribute("animatable");this.C.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===
a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.B(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.h,this.C];for(const d of c)d&&(b?_ds.B(this,a,"",d):
d.removeAttribute(a))}"fixed"===a&&this.R()}async init(a=!0){if(this.D){this.C.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.v=this.querySelector(".devsite-mobile-nav-bottom");_ds.B(this,"top-level-nav","");this.v&&this.v.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.B(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.B(this,b,"",
this.background);!this.hasAttribute("hidden")&&a?(MM(this),NM(this),await PM(this)):(await _ds.gj(),await OM(this))}}async Ta(a){var b;a?(a=a.querySelector("nav")||null,MM(this,a),NM(this,a),a&&(await JM(this),this.F.clear(),IM(this,a,!1)),_ds.Mg(this,this.querySelector("nav"),a)):_ds.Kh(this);this.J&&(KM(this),this.j&&(this.j.value="",null===(b=this.H)||void 0===b?void 0:b.classList.add("hidden")));await _ds.gj();await this.init(!1)}};RM.prototype.updateContent=RM.prototype.Ta;
RM.prototype.attributeChangedCallback=RM.prototype.attributeChangedCallback;RM.prototype.disconnectedCallback=RM.prototype.disconnectedCallback;RM.prototype.connectedCallback=RM.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",RM)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
